### ISSUE TITLE
#:font-size clobbers font size for other widgets

### ISSUE THREAD

**Issue by takikawa** [mflatt/slideshow-repl#5]
Using the `#:font-size` keyword for one widget (e.g., a `module-area`) will also clobber the font size for other widgets (e.g., a `result-area`). Is it possible to control font size independently for each widget?

**Comment by mflatt** [comment]
I'll add an `#:own-size?` option so that a pict can have its own size without affecting others.

**Comment by takikawa** [comment]
Thanks!
