### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by cwebber** [mflatt/slideshow-repl#6]
I'm guessing it's probably the same as Racket, but it would be good to have a LICENSE file along with this fine code!

**Comment by spdegabrielle** [comment]
@cwebber created PR #8 with same license as other slideshow libraries 
e.g. https://github.com/racket/slideshow/blob/master/slideshow-plugin/LICENSE.txt

**Comment by spdegabrielle** [comment]
@cwebber PR #8 merged 👍 
you can close this issue.

**Comment by cwebber** [comment]
Thank you!
